name: Mening Counter Dasturim

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  buil: 
    runs-on: windos-latest
      steps:
        -uses: action/checkout@v2
        -uses: subosito/flutter-action@v1
        with: 
          flutter-version: "3.x"
        -run: flutter pub get
        -run: flutter analyze
        -run: flutter test
        -run: flutter build apk
        # Upload generated apk to the artifacts.
        -uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/apk-release.apk